
version: 2.1

executors:
  amd64:
    docker:
      - image: cimg/base:current
    environment:
      PLATFORM: "linux/amd64"
      EXECUTOR: "amd64"
  arm64:
    docker:
      - image: cimg/base:current
    resource_class: arm.large
    environment:
      PLATFORM: "linux/arm64"
      EXECUTOR: "arm64"

jobs:
  build:
    parameters:
      platform:
        type: executor
    executor: << parameters.platform >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Full Build"
          command: |
            docker build -f Dockerfile.full -t askem-beaker .
workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              platform: [amd64, arm64]
