
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Full Build"
          command: |
            docker build -f Dockerfile.full -t askem-beaker .
workflows:
  build:
    jobs:
      - build
