---
version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: "3s"
      timeout: "3s"
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"
